// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuE75bFFz3oiJwCFmBXS_vYIgZyHxZwKw',
    appId: '1:44372176033:web:c6b968118e270727e194e0',
    messagingSenderId: '44372176033',
    projectId: 'payload-surveillance-8b5a7',
    authDomain: 'payload-surveillance-8b5a7.firebaseapp.com',
    databaseURL: 'https://payload-surveillance-8b5a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'payload-surveillance-8b5a7.firebasestorage.app',
    measurementId: 'G-1DZ4C7H5WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoP-ckKrPrsaOGygO4ud_DOxpFkhh3VXI',
    appId: '1:44372176033:android:0fbec52dea3caaa4e194e0',
    messagingSenderId: '44372176033',
    projectId: 'payload-surveillance-8b5a7',
    databaseURL: 'https://payload-surveillance-8b5a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'payload-surveillance-8b5a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIQbiqyWK8r576e7grEWij-5ce9Aunow',
    appId: '1:44372176033:ios:2a9e492c767597ade194e0',
    messagingSenderId: '44372176033',
    projectId: 'payload-surveillance-8b5a7',
    databaseURL: 'https://payload-surveillance-8b5a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'payload-surveillance-8b5a7.firebasestorage.app',
    iosBundleId: 'com.example.payloadsurveillanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIQbiqyWK8r576e7grEWij-5ce9Aunow',
    appId: '1:44372176033:ios:2a9e492c767597ade194e0',
    messagingSenderId: '44372176033',
    projectId: 'payload-surveillance-8b5a7',
    databaseURL: 'https://payload-surveillance-8b5a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'payload-surveillance-8b5a7.firebasestorage.app',
    iosBundleId: 'com.example.payloadsurveillanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuE75bFFz3oiJwCFmBXS_vYIgZyHxZwKw',
    appId: '1:44372176033:web:869881c43863cbb4e194e0',
    messagingSenderId: '44372176033',
    projectId: 'payload-surveillance-8b5a7',
    authDomain: 'payload-surveillance-8b5a7.firebaseapp.com',
    databaseURL: 'https://payload-surveillance-8b5a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'payload-surveillance-8b5a7.firebasestorage.app',
    measurementId: 'G-KWZ2284NJG',
  );
}
